// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef SERVIDORENDPOINTS_H
#define SERVIDORENDPOINTS_H

#include <ngrest/common/Service.h>
#include <string>
#include <vector>
#include <cstdlib>
#include <fstream>

#include "esenciales.h"
#include "Dia.h"
#include "Curso.h"
#include "Version.h"
#include "Horario.h"
#include "Estudiante.h"
#include "MatrizDispersa.h"
#include "MatrizOrtogonal.h"
#include "MatrizHibrida.h"
#include "Arbol.h"

struct SesionSerial
{
    std::string usuario;
    std::string password;

    /*{"usuario":"Ozmar Escobar", "password": "12345"}*/
};

struct EstudianteSerial
{
    std::string carne;
    std::string dpi;
    std::string nombre;
    std::string apellidos;
    std::string fechaNacimiento;
    std::string direccion;
    std::string creditos;
    std::string password;
    //{"carne": 201256812, "dpi": 2020556340103, "nombre":"Manuel Carlos", "apellidos": "Lopez Santos", "fechaNacimiento": "13/08/1996", "direccion":"Zona 2 el Gallito", "creditos":0, "password":"a"}
};

struct DiaSerial
{
    std::string dia;
    std::string hora_in;
    std::string hora_fin;
    //{"dia":"lunes", "hora_in":"7:10", "hora_fin":"8:50"}
};

struct HorarioSerial
{
    std::string yyyy;
    std::string ciclo;
    std::string version;
    //{"yyyy":"lunes", "ciclo":"7:10", "version":"8:50"}
};

struct CursoSistemaSerial
{
    std::string codigo;
    std::string nombre;
    std::string seccion;
    std::string edificio;
    std::string salon;
    std::string catedratico;
    std::vector<struct DiaSerial> horario;

    /*{"codigo":"149","nombre":"curso 149","seccion":"nombre 149","edificio":"T 7","salon":"149149","catedratico":"catedratico 149",
    "horario":[{"dia":"lunes","hora_in":"14:50","hora_fin":"16:30"},{"dia":"martes","hora_in":"14:50","hora_fin":"16:30"},{"dia":"miercoles","hora_in":"14:50","hora_fin":"16:30"},{"dia":"viernes","hora_in":"14:50","hora_fin":"16:30"}]}*/
};






//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: server
class ServidorEndpoints: public ngrest::Service
{
public:

///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////
///////////////////////////////////////////METODOS DEL ESTUDIANTE//////////////////////////////////////////////

    // *method: GET
    // *location: EstudianteActual
    //! Obtiene estudiante actual
    std::string GetEstudianteActual();

    // *method: GET
    // *location: TieneImagen
    //! Obtiene estudiante actual
    std::string TieneImagen();

    // *method: POST
    // *location: IniciarSesion
    //! Manda datos de sesion, retorna mensaje de fracaso si no coinciden usuario/pass, la pass por defecto de cada usuario es 12345 y usuario debe ser su nombre
    struct SesionSerial IniciarSesion(struct SesionSerial sesion);

    // *method: GET
    // *location: CerrarSesion
    //! Manda datos de sesion, retorna mensaje de fracaso si no coinciden usuario/pass, la pass por defecto de cada usuario es 12345 y usuario debe ser su nombre
    std::string CerrarSesion();


//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////
//////////////////////////////////METODOS DEL SISTEMA/ADMINISTRADOR//////////////////////////////////////////////

    // *method: POST
    // *location: SetCicloActual
    //! valida el funcionamiento de Administrar_Horarios
    std::string SetCicloActual(std::string yyyy, std::string ciclo);

    // *method: GET
    // *location: GetCicloActual
    //! Utilizado para habilitar el boton en AdminCP
    std::string GetCicloActual();

    // *method: POST
    // *location: InsertarHorario
    //! Inserta un horario con un yyyy, ciclo, pero con versiones vacias
    std::string InsertarHorario(struct HorarioSerial nuevo);

    // *method: GET
    // *location: BuscarHorarios
    //! Regresa un string: 2016$2130$12390, para validar el funcionamiento de insertar curso, llena combobox yyyy
    std::string BuscarHorarios();

    // *method: POST
    // *location: BuscarCiclos
    //! Regresa un string: primer_semestre$segundo_semestre, para validar el funcionamiento de insertar curso, llena combobox ciclos..
    std::string BuscarCiclos(std::string yyyy);

    // *method: POST
    // *location: BuscarVersiones
    //! Regresa un string: version1$version12$version122, para validar el funcionamiento de insertar curso, llena combobox versiones..
    std::string BuscarVersiones(std::string yyyy, std::string ciclo);

    // *method: GET
    // *location: VisualizarTodosHorarios
    //! Grafica y visualiza solo los horarios con los años disponibles
    std::string VisualizarTodosHorarios();

    // *method: POST
    // *location: VisualizarHorario
    //! Visualiza un solo año pero con sus ciclos y lista de versiones con cursos
    std::string VisualizarHorario(std::string buscado);

    // *method: POST
    // *location: VisualizarCiclo
    //! Visualiza un año con ciclo y todas las versiones que tiene con los codigos de cursos
    std::string VisualizarCiclo(struct HorarioSerial ciclo);

    // *method: POST
    // *location: BuscarHorario
    //! Busca un solo año para poder eliminar o visualizar
    std::string BuscarHorario(std::string buscado);

    // *method: POST
    // *location: EliminarHorario
    //! Deja de apuntar a un año, perdiendo toda la informacion contenida
    std::string EliminarHorario(std::string eliminado);

    // *method: POST
    // *location: InsertarCursoSistema
    //! Inserta cursos si no existen (codigo y seccion), retorna mensaje de insercion si fue aplicable
    std::string InsertarCursoSistema(struct CursoSistemaSerial nuevo, struct HorarioSerial ciclo);

    // *method: POST
    // *location: ModificarCursoSistema
    //! Inserta cursos si no existen (codigo y seccion), retorna mensaje de insercion si fue aplicable
    std::string ModificarCursoSistema(struct CursoSistemaSerial nuevo, struct HorarioSerial ciclo,std::string viejo);

    // *method: POST
    // *location: BuscarCursoSistema
    //! Inserta cursos si no existen (codigo y seccion), retorna mensaje de insercion si fue aplicable
    struct CursoSistemaSerial BuscarCursoSistema(std::string buscado, struct HorarioSerial ciclo);

    // *method: POST
    // *location: EliminarCursoSistema
    //! Inserta cursos si no existen (codigo y seccion), retorna mensaje de insercion si fue aplicable
    std::string EliminarCursoSistema(std::string eliminado, struct HorarioSerial ciclo);

    // *method: POST
    // *location: VisualizarCursoSistema
    //! visualiza un curso en el ciclo especificado
    std::string VisualizarCursoSistema(std::string visualizado, struct HorarioSerial ciclo);

    // *method: POST
    // *location: InsertarEstudiante
    //! Inserta estudiantes si no existen (carnet), retorna mensaje de insercion si fue aplicable
    std::string InsertarEstudiante(struct EstudianteSerial nuevo);

    // *method: POST
    // *location: BuscarEstudiante
    //! Busca estudiante para poder editar data, retorna mensaje de exito o fracaso
    struct EstudianteSerial BuscarEstudiante(std::string usuario);

    // *method: POST
    // *location: ModificarEstudiante
    //! Sobreescribe datos, mantiene imagen y horarios
    std::string ModificarEstudiante(struct EstudianteSerial nuevo, std::string viejo);

    // *method: POST
    // *location: EliminarEstudiante
    //! Elimina sin mas
    std::string EliminarEstudiante(std::string eliminar);

    // *method: POST
    // *location: VisualizarEstudiante
    //! Grafica y Visualiza un estudiante con su data, retorna URL
    std::string VisualizarEstudiante(std::string visualizado);

    // *method: GET
    // *location: ArbolBinario
    //! Recorre arbol y graphviz
    std::string GraficarArbol();

    // *method: POST
    // *location: LineaImagen
    //! Parsea el string de imagen y si es correcto se la asigna al estudiante
    std::string SetLineaImagen(std::string text);

    // *method: POST
    // *location: Contrasena
    //! Setea la password
    std::string SetContrasena(struct SesionSerial sesion);

    // *method: POST
    // *location: Matriz
    //! Obtiene una imagen de la matriz enviada, y si es usuario se la asigna
    std::string GenerarMatriz(std::string usuario);
};


#endif // SERVIDORENDPOINTS_H



